package pojos;
// Generated Feb 1, 2011 6:53:29 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Busfare generated by hbm2java
 */
public class Busfare  implements java.io.Serializable {


     private int fareid;
     private Busroute busroute;
     private int ac;
     private int semiluxury;
     private int sleeper;

    public Busfare() {
    }

    public Busfare(int fareid, Busroute busroute, int ac, int semiluxury, int sleeper) {
       this.fareid = fareid;
       this.busroute = busroute;
       this.ac = ac;
       this.semiluxury = semiluxury;
       this.sleeper = sleeper;
    }
   
    public int getFareid() {
        return this.fareid;
    }
    
    public void setFareid(int fareid) {
        this.fareid = fareid;
    }
    public Busroute getBusroute() {
        return this.busroute;
    }
    
    public void setBusroute(Busroute busroute) {
        this.busroute = busroute;
    }
    public int getAc() {
        return this.ac;
    }
    
    public void setAc(int ac) {
        this.ac = ac;
    }
    public int getSemiluxury() {
        return this.semiluxury;
    }
    
    public void setSemiluxury(int semiluxury) {
        this.semiluxury = semiluxury;
    }
    public int getSleeper() {
        return this.sleeper;
    }
    
    public void setSleeper(int sleeper) {
        this.sleeper = sleeper;
    }




}


