package pojos;
// Generated Feb 1, 2011 6:53:29 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Busstop generated by hbm2java
 */
public class Busstop  implements java.io.Serializable {


     private int stopid;
     private Businfo businfo;
     private String place;
     private String uptime;
     private String downtime;
     private int headsign;

    public Busstop() {
    }

    public Busstop(int stopid, Businfo businfo, String place, String uptime, String downtime,int headsign) {
       this.stopid = stopid;
       this.businfo = businfo;
       this.place = place;
       this.uptime = uptime;
       this.downtime = downtime;
       this.headsign = headsign;
    }
   
    public int getStopid() {
        return this.stopid;
    }
    
    public void setStopid(int stopid) {
        this.stopid = stopid;
    }
    public Businfo getBusinfo() {
        return this.businfo;
    }
    
    public void setBusinfo(Businfo businfo) {
        this.businfo = businfo;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public String getUptime() {
        return this.uptime;
    }
    
    public void setUptime(String uptime) {
        this.uptime = uptime;
    }
    public String getDowntime() {
        return this.downtime;
    }
    
    public void setDowntime(String downtime) {
        this.downtime = downtime;
    }
    public int getHeadsign() {
        return this.headsign;
    }
    
    public void setHeadsign(int headsign) {
        this.headsign = headsign;
    }




}


