package pojos;
// Generated Feb 1, 2011 6:53:29 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;

/**
 * Userregistration generated by hbm2java
 */
public class Userregistration  implements java.io.Serializable {


     private String emailid;
     private String firstname;
     private String lastname;
     private String password;
     private String gender;
     private String dob;
     private double mobileno;
     private String address;
     private Set passengerinfos = new HashSet(0);

    public Userregistration() {
    }

	
    public Userregistration(String emailid, String firstname, String lastname, String password, String gender, String dob) {
        this.emailid = emailid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.gender = gender;
        this.dob = dob;
    }
    public Userregistration(String emailid, String firstname, String lastname, String password, String gender, String dob, double mobileno, String address, Set passengerinfos) {
       this.emailid = emailid;
       this.firstname = firstname;
       this.lastname = lastname;
       this.password = password;
       this.gender = gender;
       this.dob = dob;
       this.mobileno = mobileno;
       this.address = address;
       this.passengerinfos = passengerinfos;
    }
   
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public double getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(double mobileno) {
        this.mobileno = mobileno;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getPassengerinfos() {
        return this.passengerinfos;
    }
    
    public void setPassengerinfos(Set passengerinfos) {
        this.passengerinfos = passengerinfos;
    }




}


